#! /usr/bin/env python

from scraperpy import core
import sys, os, time

print(sys.version)

if len(sys.argv) < 1:
    print("PYG-SCRAPERPY: Generates a news feed from different news websites, and posts them to a mongoDB")
    print("USAGE: ./pyg-scraperpy <BBCArabic|BBCArabicRSS> <url-to-mongo-db>")
else:
    print("Scraping the latest news from ..." + sys.argv[1])
    mongourl = sys.argv[2]
    if sys.argv[1] == 'BBCArabic':
        core.getBBCArabic(mongourl)
    elif sys.argv[1] == 'BBCArabicRSS':
        core.getBBCArabicRSS(mongourl)
    else:
        print('Unable to scrape that site yet')


