#! /usr/bin/env python

from scraperpy import core
import sys, os, time

print(sys.version)

if len(sys.argv) < 1:
    print("PYG-SCRAPERPY: Generates a news feed from different news websites"
    print("USAGE: ./pyg-scraperpy <BBCArabic> <directory-to-put-files>")
else:
    print("Scraping the latest news from ..." + sys.argv[1])
    timestr = time.strftime("%Y%m%d-%H%M%S")
    os.makedirs(sys.argv[2], exist_ok=True)
    filename = os.path.join(sys.argv[2], timestr + '_scraped.txt')
    if sys.argv[1] == 'BBCArabic':
        core.getBBCArabic(filename)
    else:
        print('Unable to scrape that site yet')





#print(core.getBBCArabic())
#print('works')
